JAVAC = javac
JFLAGS = -g

SOURCES = ParallelFiltering.java SequentialFiltering.java Main.java Test.java Driver.java

.SUFFIXES:  .java  .class

.java.class:
	$(JAVAC)  $(JFLAGS)  $<


Driver.class: ParallelFiltering.class SequentialFiltering.class Main.java Test.class Driver.java

clean:
	@rm -f  $(SOURCES:.java=.class)
